### ISSUE TITLE
Fix: mode Color unsupported, need mode "24bit Color"...

### ISSUE THREAD

**Issue by toxic0berliner** [sbs20/scanservjs#11]
I got this working in a docker container running ubuntu and passing my brother MFC-7320 through to docker.

This works perfectly in grey, but fails in mode color.
I confirmed by hacking your Scanimage class, when you add the mode onto the cmd line, you pass Color, no quotes, passing "24bit Color" (with quotes) works fine for me.

Any way you can give us the option to setup ? Or autodetect ?
I'm using following scanimage version : `scanimage (sane-backends) 1.0.27; backend version 1.0.27`

I didn't just invent "24bitColor", it showed in the help of scanimage (scanimage -h)

**Comment by sbs20** [comment]
Thanks for reporting this. Could you share your `device.conf` please? It gets created on first run.

I just want to check that it's in there already - then it'll be easier to fix.

**Comment by sbs20** [comment]
I'm working on it but it's reasonably involved. The code just doesn't use `device.conf` to get modes - it needs to. But by all means work on it too. You may beat me to it.

The code needs to run `scanimage -A` in order to get all the options and create `device.conf`. In order to fully support the options I'm having to change the `device.conf` format so I'm having to introduce a version too.

I can guarantee that so long as `device.conf` exists and `scanservjs` isn't upgraded then `scanimage -A` won't be run.

**Comment by toxic0berliner** [comment]
Well, sadly I'm not equipped to do some JS DEV, so last time I tried to clone and build it failed somewhere at the very beginning (missing gulp or something similar...) 
So if it's not too hard for you I'd appreciate a release package, even flagged as dev, I'll just update my dockerfile to pull from it and it can be tested in a pinch.

**Comment by sbs20** [comment]
No worries. Try [this](https://github.com/sbs20/scanservjs/releases/tag/v1.0.1)

**Comment by sbs20** [comment]
Great - thanks for testing and your help - I really appreciate it. My scanner doesn't have any modes with spaces so it never came up. Will sort.

The `device.conf` revamp is correct here.
> I can guarantee that so long as device.conf exists **and scanservjs isn't upgraded** then scanimage -A won't be run.
This is a scanservjs upgrade - the `device.conf` has to change because the old one didn't have the modes (it only had the default).

Finally, that's **really** weird about Firefox - it's my main browser (in fact I'm guilt of *only* testing with it) - I'm on 62.0.3. Any chance you could press F12 and see if anything comes up in the console?
