### ISSUE TITLE
Multi-page preview

### ISSUE THREAD

**Issue by lewisbolaton** [sbs20/scanservjs#113]
I already tried this package with my HP All-in-One printer/scanner with my Raspberry Pi 3B+ and it works flawlessly. However, it seems like committing mistakes when scanning multiple pages was not taken into consideration yet. For example, if I am scanning multiple pages and the current page I am scanning was not aligned properly, the only option I have is to prematurely finish the scan or continue with the misaligned page.

Related: I think pressing the scan should also change the preview and user should have an option whether the scanned document should be saved or not.

**Comment by sbs20** [comment]
On a manual batch scan the new version (when it's released) will preview the image to the user and prompt to rescan or move to the next image.

> Related: I think pressing the scan should also change the preview and user should have an option whether the scanned document should be saved or not.

Unfortunately, updating the preview itself is more tricky since cropping can change the aspect ratio and throw off the cropper logic. It's not impossible but it's more work. I'll create a separate issue.
