### ISSUE TITLE
Make scan geometry work to 1dp

### ISSUE THREAD

**Issue by lewisbolaton** [sbs20/scanservjs#118]
My printer/scanner specifies that 216 mm is its maximum scan width (as wide as US Letter paper). However, it looks like the maximum value of width from the web interface is only up to 215. Is there any way to change the scan width to exactly 216 mm so that the output file will have the exact dimension as a paper of size US Letter?

**Comment by sbs20** [comment]
Hi. Can you run `scanimage -A > scanimageA.txt` and upload the file here please?

Most likely the scanner (or scanimage) is reporting `215.9` or something.

**Comment by lewisbolaton** [comment]
Yes, it looks like my scanner has a maximum scan width of 215.9 mm which is exactly 8.5 in when converted (apologies for the imperial units nuisance). Maybe we can have an option to fetch this maximum value from `scanimage`, if you haven't implemented it yet, rather than have it hardcoded like the one shown below?

https://github.com/sbs20/scanservjs/blob/f9f2639d1e19334c7c852d211ab6ea68ab0c4bb3/client/components/Scanserv.vue#L169-L180

Another approach might be to add another component which has predefined sizes (ISO A4, US Letter, etc.) and let this affect the width and height input components appropriately.

**Comment by sbs20** [comment]
Haha - don't worry, we're stuck with the imperial unit hangover too.

The code quoted above is just a default value so the UI doesn't bork before it's got the real values from the backend. The actual culprit here is in [this](https://github.com/sbs20/scanservjs/blob/f9f2639d1e19334c7c852d211ab6ea68ab0c4bb3/server/device.js#L36) function. I deliberately made the decision to floor the results of parsing the scanner config. I seem to recall - but can't find any evidence - that it was because there were some cases of scanimage not liking the results.

I will remove it and retest to see what happens.

**Comment by sbs20** [comment]
Ok. I remember why it is now. 

The cropper component in the UI has some logic to convert between pixels on screen to and from mm geometry. The pixel geometry is imperfect since it is integer based (there are no half pixels) and are based on the dimensions of the preview image. As a result, the values that actually get written to the fields (which are ultimately the ones sent up to the scanner to scan) get rounded. I had it all set up to just work to the nearest mm and to round down. It's predicable and reliable but causes a problem for you.

I have experimented and put 1dp rounding in place throughout. I now have a situation where the maximum dimensions I can select are `297x214.8` even though my scanner allows larger. There could also be the inverse case where the geometry ends up being too large and borking the scan request.

I need to think on this more and do more experimentation.

**Comment by lewisbolaton** [comment]
It might be because the dimensions are constantly being converted (sort of like a loop) until those dimensions are achieved by the cropper component and width component. Sort of like when `onCoordinates()` is called (conversion occurs) then `onCrop()` is called too (conversion occurs again) looping until both values from the cropper and width component match (about 214.8 mm in your case).

Maybe we can have another class to hold the true dimensions without it constantly changing?

**Comment by sbs20** [comment]
So the actual reason for the problem was that the preview process creates a scaled version of the scanned image. That scaled version is at a moderately low resolution. Images have an exact number of pixels. So in certain cases, the exact aspect ratio of the preview was very slightly off from the aspect ratio of the scanner (as defined by its x / y max values).

The UI was assuming the two aspect ratios were the same and deriving a single scaling factor (from the height, but would have given the inverse problem if it used the width). This will have worked to 0dp precision but not for 1dp.

The solution is to calculate a horizontal AND vertical scaling factor from the resolution.
