### ISSUE TITLE
Feature Request: Add support for Brother scanners

### ISSUE THREAD

**Issue by hacker-h** [sbs20/scanservjs#171]
To support Brother scanners you need an additional proprietary driver.
It can be downloaded and installed like this:
```
curl https://download.brother.com/welcome/dlf104033/brscan5-1.2.6-0.amd64.deb -o brscan5.deb \
  && apt-get install ./brscan5.deb \
  && rm ./brscan5.deb
```
With this modification to the Dockerfile it works for me with a brother scanner.

You can also fetch the latest download URL if you want:
```
curl -s "https://support.brother.com/g/b/downloadhowto.aspx?c=us_ot&lang=en&prod=ads2400n_all&os=128&dlid=dlf104033_000&flang=4&type3=566" | grep '\.deb' | cut -d'=' -f3 | cut -d'"' -f2
```

Would highly appreciate such a feature upstream, what is your preferred way of dealing with such proprietary drivers?

Note: this will only work for amd64 architectures

**Comment by sbs20** [comment]
I'm thinking about how best to achieve this. I'm reluctant to add more to the core image - if anything I'm looking to slim it down. In the mean time it might be possible to create a new image from the base image and install the drivers in there.

**Comment by hacker-h** [comment]
Agree, I could imagine individual image tags for each custom driver e.g. brother, canon, hp etc.

**Comment by sbs20** [comment]
Hi. I've updated the [documentation](https://github.com/sbs20/scanservjs/blob/master/docs/docker.md#accessing-hardware). Having thought about this, I am more certain that I don't want to add further backends to the core image - if anything, I'm even considering removing the `sane` package so that there are **no** backends in the image - although I'm still on the fence about it.

In case it's helpful, there is now an [improved installation script](https://github.com/sbs20/scanservjs/blob/master/docs/install.md#manual-steps) for non-docker installs which may make your life easier.
