### ISSUE TITLE
FEATURE REQUEST: Translatable modes and sources

### ISSUE THREAD

**Issue by ceskyDJ** [sbs20/scanservjs#209]
Hi, there are still a few things that can't be translated now. It's mainly items from "Source" and "Mode" selects inputs. It will be good if you add support for translating these things.

Btw, the Czech translation is:

Source:
- Flatbad: Skenovací deska

Mode:
- Color: Barevný
- Gray: Černobílý
- Lineart: Perokresba

**Comment by sbs20** [comment]
Hi. That's a reasonable point. The difficulty is that these items come from the SANE backends. While many of the values are common, they are ultimately vendor specific and will vary. E.g. source might be `Automatic Document Feeder` or `ADF` or `Automatic Document Feeder (left aligned)`.

In order to work properly there would need to be translations for every possible value, which can't be known.

As far as I can tell, the source for the backends localisation lives here: https://gitlab.com/sane-project/backends/-/tree/master/po

Even so, there is still the possibility of manufacturers shipping their own drivers with unexpected values. At that point, it becomes a matter of trying to gracefully fallback to the raw value.

I will look at this further, but I just wanted you to know there was a reason this hadn't been done!

**Comment by ceskyDJ** [comment]
Thanks for reply. I didn't know about this problem. I have tested sane with only a few scanner and every one of them have the same values. The main reason is there are many types of scanners, I think. What about color mode? There aren't too many items for "Mode" in the translation file at your link.

**Comment by sbs20** [comment]
No problem. Ultimately it's the same problem for mode: `Color`, `24bit Color` etc.

Nonetheless, I will look into it. If I can get it to fallback gracefully then I will do it.

**Comment by ceskyDJ** [comment]
Hmm, is there only a problem with color depth? It could be solved with regexes.

**Comment by sbs20** [comment]
I've got something which should hopefully handle the majority of scanner manufacturers. I need a few additional translations - you'll see the missing ones [here](https://github.com/sbs20/scanservjs/blob/86fab6783f74997e368a2e5a17f67cbd95c3783b/webui/src/locales/cs.json#L39)
