### ISSUE TITLE
Configurable device names

### ISSUE THREAD

**Issue by ceskyDJ** [sbs20/scanservjs#212]
Hi, your app shows devices as there addresses. It's really good for accurate identification but it's not too nice for quick-reading and selecting the right device. "Blue scanner in Ben's room" is always better than "hpaio:/net/Printer_Model_Name_series?ip=192.168.11.31&queue=false", isn't it?

There is one main problem - where to edit the names. Devices are stored in config files - can I change the name without problems? It could be the solution :D.

**Comment by sbs20** [comment]
The device name is needed in order to execute a scan (certainly with multiple scanners). So it's not possible just to change the name. The only solution I can think of is to allow users to create their own map of deviceids to names:

```javascript
config.deviceNames = {
  'hpaio:/net/Printer_Model_Name_series?ip=192.168.11.31&queue=false': 'Blue scanner in Ben's room',
  'net:10.0.7.129:airscan:e0:Canon TR8500 series-5': 'Green scanner in the corner'
};
```

That could then get sent to the UI and it could do the rest.

But this would be susceptible to scanner device id changes (IP address / USB port). Or you could make it do a regex match, but then that's getting even more complicated.

I'm happy to leave this issue open for a while to see if there's other interest, but I'm not convinced it's worth the effort given that the solution still wouldn't be great and I'm not convinced this would be widely used.

**Comment by xxjkzs** [comment]
I would vote yes for this feature. Especially when the devices are all the same brand or  even same model.
Not everyone knows what those long string means besides the one who set them up. If they have problems, users won't read that weird string to debug themselves anyway. It's better to make the users easier to tell which machine they are using.

**Comment by sbs20** [comment]
See: https://github.com/sbs20/scanservjs/blob/master/docs/config.md#friendly-device-name

**Comment by ceskyDJ** [comment]
Thanks a lot for adding this feature!
