### ISSUE TITLE
Graceful upgrade of device and request versioning

### ISSUE THREAD

**Issue by ceskyDJ** [sbs20/scanservjs#245]
Hi! I have tried to setup automatic updating of this app on my Raspberry Pi. It's simple Bash script that runs installation with curl command as you specify in docs/install.md. It works well but there is a little problem with this way - if new version is available, it is installed and all my configurations are lost. All means cached devices and all options in "Scan" page. I don't know if it resets locale and theme (I use default ones at the device I test autoupdating on).

So, the question is: Is it normal behaviour or a bug? If it's normal, could you look at it and add support for updating, please? If it's a bug, let me know and I'll send you more information (specifying what could help you will be good). I'm sorry for my passive access, I don't have too much time for looking at your installation Shell script right now.

**Comment by sbs20** [comment]
I need to investigate, but off the top of my head, this is expected behaviour right now. Each time the scan page loads, it checks to see if the stored settings version matches the server - if not, if gets it again. The server does the same thing when looking at devices. The reason is does it in for cases where the devices / configuration structure changes between versions.

Let me look in more detail and see if there's a neater way.

**Comment by sbs20** [comment]
Hi. In case you haven't noticed already, the location of the install script has changed with the repo restructure. I've updated the documentation on the install page though.

**Comment by ceskyDJ** [comment]
Hello, thanks for message. I haven't known about it till now.
