### ISSUE TITLE
Suggestion: Manual Batch with additional preview and crop for each page

### ISSUE THREAD

**Issue by r7l** [sbs20/scanservjs#279]
After scanning quite a number of documents, i've tried the batch process to get multiple documents into a single PDF.

The batch process itself works pretty good. But given you have a flatbet scanner and a bunch of documents that weren't printed with perfect alignment, it would be really helpful to allow additional previews and cropping for each of the pages within the manual batch process. Right now, it will always use the one from the first page.

**Comment by sbs20** [comment]
Thanks for the suggestion. The current behaviour is that cropping is selected prior to scan (though probably after preview) and is a function of the scan itself (geometry is sent to the scanner), rather than post processing. This has some speed advantages on older slower scanners.

In order for this feature to work, the scan would be of the full dimensions and either a further scan for cropping (not great) or post processing for a crop (better).

This would be a pretty significant update / rewrite and result in something which, in my view, would be inferior to many existing image processing tools. 

I think a workflow which performs full dimension scans to a zip of raw images, which are then processed in something like GIMP, Photoshop or even Irfanview would probably offer more reliable and better results. I know it's not such a clean workflow as your proposal, but it's certainly less effort and probably better in terms of quality.

I will continue to think about this but for now at least I don't think I'm going to do it.

**Comment by r7l** [comment]
I migth not have enough insight of the batch process and how it works to understand why it would end up being inferior. Maybe it would not work as an extension to the current manual batch process but instead being implemented as a "full" manual batch, where you would actually be able to run additional preview scans and set scanner dimensions. So basically don't have this overlay but instead put those button above the main UI and loop thought the main process and put everything together after it. 

You might be right that it might return better results when using Gimp / PS. Not sure if that's still the case if you scan PDF + OCR as i was doing all day. But even so, if you see this feature as something that would require allot of rewriting, i fully understand you for not implementing it. Scanservjs is awesome already and it's a blaze to work with.

**Comment by sbs20** [comment]
> But even so, if you see this feature as something that would require allot of rewriting, i fully understand you for not implementing it. Scanservjs is awesome already and it's a blaze to work with.

Thank you - I appreciate it!

I suppose when I say "inferior" I'm thinking about all possible futures.

The scan process is really multiple actions in one: scanning; managing intermediate images; clean up (filtering, cropping, rotating etc); resizing; compressing; merging. My original objective with the software was always to take care of the actual scanning - solving the problem of scanner drivers and availability of the hardware. It always seemed that it would be useful to have it served and avoid having to install manufacturer software on every client. We already have other software to do the other tasks.

When implementing things like resolution, cropping, filtering, OCR, multipage / batch, PDFs this was, for me, always about solving the common, obvious problems for 80% users quickly rather than a full featured application. I can scan to PDF and send back to someone with a degree of control. It may be rough around the edges, but it works.

To be coarse about it, I'm not going to implement photoshop (or GIMP) in this (not that you're suggesting that, I know). In **this** sense, this will always be inferior. The "blur" filter has no parameters - it just blurs a bit. JPG compression has no granularity - just a few canned choices (HIGH / MED / LOW). I'm not going to implement fine rotation. And so on.

So the problem is, where do I draw the line? What do I implement, and what don't I? My guiding principle tends to be a balance between my time and what I can see as being commonly asked-for features.

> So basically don't have this overlay but instead put those button above the main UI and loop thought the main process and put everything together after it.

Indeed. There would need to be a way of grouping the images together so that the software can merge them after - and know which images to merge. At the moment, this all happens "within" the scan itself. Of course, it **could** be done and it might not be **that** hard, but it impacts a whole load of other code which is (hopefully) quite stable. More though, if each page could be cropped individually, then each page will inevitably have different dimensions. Some users may be happy with that, others not. So another option to track and handle. Etc etc.

I say all this not to argue, just to try and offer an explanation as to why I am (currently) reluctant.

I do appreciate the thoughtful comments and feedback though. This software has improved immeasurably due to everyone's testing, contributions, issues and care. Don't stop!
