### ISSUE TITLE
Synology docker permissions issue

### ISSUE THREAD

**Issue by hoangtridung** [sbs20/scanservjs#333]
**Describe the bug**
Browse to address "[HOST_IP]:[HOST-PORT]", the msg. appear: "Found no devices"

**Client.**
 - Browser MS Edge
 - Version on MS Windows10

**Server **
 - OS: DSM 6.2.3-25426 Update 3 on DS3617xs
 - Docker version 20.10.3-0554 and "SANE Backends" package

**Logs**
"
2021-08-11 09:18:47 | stdout |  
-- | -- | --
2021-08-11 09:18:47 | stdout | scanimage: open of device net:192.168.103.4:snapscan:libusb:002:008 failed: Invalid argument
2021-08-11 09:18:47 | stdout | [2021-08-11T09:18:47.841Z] ERROR (Devices): Ignoring net:192.168.103.4:snapscan:libusb:002:008. Error: Error: Command failed: /usr/bin/scanimage -d 'net:192.168.103.4:snapscan:libusb:002:008' -A
2021-08-11 09:18:46 | stdout |  
2021-08-11 09:18:46 | stdout | [2021-08-11T09:18:46.834Z] DEBUG (Devices): Device list:  device `net:192.168.103.4:snapscan:libusb:002:008' is a Acer FlatbedScanner13 flatbed scanner
2021-08-11 09:18:39 | stdout | [2021-08-11T09:18:39.834Z] DEBUG (Devices): Config.devices:  []
2021-08-11 09:18:39 | stdout | [2021-08-11T09:18:39.834Z] DEBUG (Devices): devices.json contains no devices. Reloading
2021-08-11 09:18:39 | stdout | [2021-08-11T09:18:39.799Z] DEBUG (Http): request:  { method: [32m'POST'[39m, path: [32m'/preview'[39m }

**Additional context**
My scanner : Acer (BenQ) Prisa 640UT connect directly to USB port on Xpenology machine. On this machine, there are DOCKER package and installed SCANSERVJS image from registry: "https://registry.hub.docker.com/r/sbs20/scanservjs/"
![Capture](https://user-images.githubusercontent.com/19668898/129007464-6d76f3df-a83f-4c5f-a56c-5a39fded4d0a.JPG)
![Capture1](https://user-images.githubusercontent.com/19668898/129007984-473cfdb2-6bde-4b13-8e68-bcb520d2f441.JPG)
![Capture2](https://user-images.githubusercontent.com/19668898/129040752-8e630c1b-6fe1-4941-8ee7-0a5c7c68c8ca.JPG)

**Comment by sbs20** [comment]
Hi. Sorry for the slow reply - I've been away. It's difficult to know exactly where the problem is but what we can see from the logs is that the software is unable to get a list of any scanners.

There are some useful debugging steps [here](https://github.com/sbs20/scanservjs/blob/master/docs/sane.md#validate-sane-is-working). Try running these directly on the NAS (I assume you're running on a Synology). If it doesn't work, then it's a problem with the snapscan install. If it does then you need to work back.

The next step would be to verify [network access](https://github.com/sbs20/scanservjs/blob/master/docs/sane.md#defining-network-scanners) - the docker image is essentially another machine (client) which is accessing your NAS (server) over the network. You can run the same host (the NAS) as both the server and client - this can help with debugging. If it all works on the same host, then it's a problem with the docker container accessing the host.

See how you get on with that for now.

**Comment by hoangtridung** [comment]
I've installed other on Rpi, connect my scanner (Acer/Benq 640UP) directly to Rpi USB port. While using "scanimage" to debug, the same error: "... failed: Invalid argument". 
Then i' founded solution is: copy Acer firmware file in /usr/share/sane/snapscan. Edit /etc/sane.d/snapscan.conf refer to that the firmware file location.
After that, "scanimage -T" response with good result.

Return to container in Sysnology, using your image and "docker-compose.yml" file.
But the command: "sudo docker-compose up -d" was failed with error:
"Building scanservjs
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /volume2/docker_config/scanservjs/Dockerfile: no such file or directory
ERROR: Service 'scanservjs' failed to build"
I can creating SCANSERVJS container using Synology GUI but don't know how to specify UID and GID to run it. In that situation, the UID and GID is 2001:2001 and it don't have enough per. to access the config folder on root machine.

How can I continuing that work ?

**Comment by sbs20** [comment]
I don't really have any real world experience with the Synology NAS and don't have one to test with. It's possible that @mbugert might be able to assist.

**Comment by mbugert** [comment]
Hi @hoangtridung, did you already try [these instructions](https://github.com/sbs20/scanservjs/blob/master/docs/docker.md#hosting-it-on-a-synology-nas-using-docker) for setting up scanservjs on a Synology machine? It's the setup I'm using on my Synology which is working okay so far.
It sounds like you additionally need proprietary drivers. In that case I would recommend to add instructions to install those to the Dockerfile before following the instructions above (that's how I did it for my Brother scanner).

Hope that helps, let us know if it doesn't. :smile:

**Comment by sbs20** [comment]
Closed due to inactivity
