### ISSUE TITLE
i386 Custom Build

### ISSUE THREAD

**Issue by capriciousduck** [sbs20/scanservjs#367]
Hi. I'm thinking to build the custom i386 docker image. However, there's no version 14 docker image(for i386). So I just wanted to know whether scanservjs would work fine with Node 12(so far the latest version available in docker hub)?

I am looking for a way to finally use my old hardware :)

**Comment by sbs20** [comment]
No idea off the top of my head, sorry. You can use anything for the builder though, it just generates the package.

**Comment by capriciousduck** [comment]
Hey, here is the repo I forked from yours. I added the Dockerfile.i386 for 32-bit docker support. Instead, do I create a pull request?

https://github.com/capriciousduck/scanservjs

**Comment by sbs20** [comment]
Have added a commit which may resolve this in the mainline

**Comment by sbs20** [comment]
Change of plan - that did not work.

**Comment by sbs20** [comment]
I don't think I'm going to take this issue any further. I'm glad you managed to resolve it for you.

Since there doesn't appear to be a `linux/386` debian node build the only way to make this work for everyone (that I know of) is to change the build process as you have. I appreciate that it works, but I would like to keep to using the standard images available.

**Comment by capriciousduck** [comment]
That's okay @sbs20. No problem :)
