### ISSUE TITLE
Arm64 build for raspberry pi

### ISSUE THREAD

**Issue by balves42** [sbs20/scanservjs#372]
Hi,

Sorry for bothering you. This project is amazing, it gave a new life to my old printer. But i needed to make some modifications to be able to run it on my raspberry pi 4 with an old HP printer so i decided to make a fork.

It's nothing fancy, it's the first time i made a docker image. You can check the fork on my repositories, i hope it's useful to someone.

Almost forgot, having your project in my native language (portuguese) was amazing!

**Comment by sbs20** [comment]
Hi! You're not bothering me at all - you're contributing! 😄 

And I love that this has given new life to your old printer. That's the whole reason I started this project - it annoyed me that I could not get 64bit drivers for Windows for my old scanner!

I am really short on time at the moment, so I'm going to make a note of the [important commit](https://github.com/balves42/scanservjs/commit/e2c1df42cc2cc6601185b44caeb830ab2182ac0a) and figure out how to deal with this properly later.

Docker has been on my mind for this project for some time - the two big issues being:

* arm64 which I've kind of ignored because there is an alternative. I want to do a multi-arch docker file but it's complicated because of SANE airscan. Airscan is now in Debian 11 (I think) but I haven't had a chance to test it running on a host with an older kernel
* using a non-root user, which is good practice but causes all sorts of issues

There is a further issue which is around installing third party drivers but I think that's more easily solved by just pulling an existing image and installing them... but it requires root.

**Comment by mkv9** [comment]
Hi. I am actually running scanservjs on my "Raspberry Pi 4 Model B" and old "HP LaserJet 3055".  HP "all in one" is connected to Raspberry pi via USB and shared via wired and wireless. I used "one line install" with "curl to bash".

It actually works ! there is a small oddity though :

It seems front end passes size that is .6 too large to scanimage and it gets rejected with error - "scanimage: setting of option --br-x failed (Invalid argument)". This can be fixed if size is manually adjusted to remove fraction > 228. But preview does not work (as it uses 228.6 which is .6 too large). 

![rpi_preview_failure](https://user-images.githubusercontent.com/95506720/144680680-071c8c6f-43b7-4ae3-98cc-e0748381a6c7.PNG)

This fails:
> scanimage --device 'hpaio:/usb/HP_LaserJet_3055?serial=00CNBK203498' --mode 'Lineart' --resolution 100 -l 0 -t 0 -x 228.6 -y 381 --format tiff 

This works:
> scanimage --device 'hpaio:/usb/HP_LaserJet_3055?serial=00CNBK203498' --mode 'Lineart' --resolution 100 -l 0 -t 0 -x 228 -y 381 --format tiff 

This works as well :
> scanimage --device 'hpaio:/usb/HP_LaserJet_3055?serial=00CNBK203498' --mode 'Lineart' --resolution 100 -l 0 -t 0 -x 227.6 -y 381 --format tiff 

Above may be issue that is specific to my old all in one HP printer.

**Comment by sbs20** [comment]
Can you share your `./config/devices.json`?

**Comment by sakana280** [comment]
I can confirm the Dockerfile in main builds and runs fine on an Odroid HC2 (`--platform linux/arm/v7`) with HP DeskJet F2180, and also builds for arm64 but i dont have any linux/arm64 hardware to test on sorry. It might be as simple as adding `platforms: linux/amd64,linux/arm64,linux/arm/v7` to the `docker/build-push-action` in this repo's docker workflow to produce cross platform docker images?

I have created [a fork](https://github.com/sakana280/scanservjs-private/tree/hplip_support) and PR #384 that supports HP scanners (via hplip package, similar to @balves42 fork). I've tried to keep the dockerfile cross platform, but that needs testing on amd64 and arm64 hardware. If anyone wants to test the hplip support on arm64, it can be built using: `docker build --platform linux/arm64/v8 --target scanservjs-core --tag scanservjshp-arm64 .` Might not need the --platform param if building on device?

I found the trick to getting the Docker container running was mapping /var/run/dbus and /dev/bus/usb plus root access ie `docker run --detach --publish 8800:8080/tcp --volume /var/run/dbus:/var/run/dbus --volume /dev/bus/usb:/dev/bus/usb --privileged --restart unless-stopped --name sane scanservjshp` As much as a non-root config would be ideal, the root access approach results in a super simple setup with no messing about with vendor ids and persistent device names. Very nice work Sam putting this app together :)

**Comment by kurtmorris** [comment]
Hi there,

I also had no issue building the dockerfile for linux/arm64. In doing so I also have created a temporary repo on Docker Hub that includes a build of scanservjs targeted for the Raspberry Pi (running 64-bit Raspbian). This will serve as an easy way for users to install scanservjs on the Pi until this repo starts building for linux/arm64. The new image was built directly from an untouched git clone.

[masterokhan/pi-scanservjs](https://hub.docker.com/r/masterokhan/pi-scanservjs)

Thank you Sam for creating such a lovely web app for scanning!

**Comment by sbs20** [comment]
Credit: #384 - thank you @sakana280 !!
