### ISSUE TITLE
Batch mode for single pages - documentation

### ISSUE THREAD

**Issue by APraxx** [sbs20/scanservjs#373]
Hi,

I was just wondering, what is the intended way to scan multiple single pages without adf in a somewhat fast way?

Currently i see two ways:
1. You scan the page as a single page but get interrupted after each scan by the file selection screen
2. You use(misuse?) the batch mode with a not multipage capable format (eg.: jpeg) and get a zip file

Option 1 seems like the natural use, but in it's current form it's not really fast, so gets tiresome quick.
Option 2 works wonderful, fast and all but seems kinda like a misuse, because with, eg. PDF, you'd get a single file.

Is there a answer to the question of the intended way?
If it's Option 1, is there a possibility that we can stay at the scan page?
If it's Option 2, it would be good to somehow communicate the use case somewhere.
Or is there an Option 3?

This is just something i noticed while using this tool, which is really useful btw thx for that.

**Comment by sbs20** [comment]
Hello!

The intention was option 2. It's not a misuse 😄 

Option 2 is actually doing a whole load of single page scans and then naming the files incrementally. Once the scan process finishes, the pipelines do their work. Some pipelines (PDF) create one file, others (JPG) create many. If the final output contains many files, then the scan process zips them all up to create a single file. This is all deliverate behaviour.

Hopefully that answers the question. If so, do you think there needs to be better communication of that? I'm always wary of documentation, because no one RTM!

**Comment by Guldoman** [comment]
I think that an option to keep the files scanned via batch mode separated would be great.

**Comment by sbs20** [comment]
> I think that an option to keep the files scanned via batch mode separated would be great.

How do you mean keep them separated? Not in a zip?

**Comment by Guldoman** [comment]
Yes, with the possibility to manage each one from the UI, as if they were scanned one by one.

**Comment by APraxx** [comment]
Thx for the reply. 

> Option 2 is actually doing a whole load of single page scans and then naming the files incrementally. Once the scan process finishes, the pipelines do their work. Some pipelines (PDF) create one file, others (JPG) create many. If the final output contains many files, then the scan process zips them all up to create a single file. This is all deliverate behaviour.

Imo is it not super obvious what will happen with option 2. someone has to try it out or know every format that is preset. e.g.: tif supports mutlipage, png i would have to research and i still wouldn't know how the end result would look like.
I think a short documentation entry can help and clarify. And i'd say people who selfhost a sane webfrontend are more incline to read the manual ;)

**Comment by sbs20** [comment]
> Imo is it not super obvious what will happen with option 2. someone has to try it out or know every format that is preset. e.g.: tif supports mutlipage, png i would have to research and i still wouldn't know how the end result would look like. I think a short documentation entry can help and clarify. And i'd say people who selfhost a sane webfrontend are more incline to read the manual ;)

Fair enough! See https://github.com/sbs20/scanservjs/commit/5addb5f4ecf20009ae323ea9d64875a1c1eddeef

**Comment by sbs20** [comment]
> Yes, with the possibility to manage each one from the UI, as if they were scanned one by one.

I appreciate your thoughts. I've given this a lot of thought and it's a lot of effort to change this behaviour (and I struggle for time these days). I don't think it's worth the effort given that there is an alternative - download the result and edit locally. I know this is much harder on tablets and phones, but it's still possible.

**Comment by gortium** [comment]
I would also like to be able to scan by batch with ADF and have multiple separated file, because I'm pointing the output folder directly into the consume folder of paperless-ngx.

Looking at this thread and the doc, I understand that I should be able to create new pipeline. After a little [research](https://unix.stackexchange.com/questions/29869/converting-multiple-image-files-from-jpeg-to-pdf-format), I found the "mogrify" command that is supposed to be able to do the same as the "convert", but with multiple files. 

I'm not used to JavaScript and the implementation of this project. I'm not sure what happen before and after the pipeline commands are executed.

@sbs20 do you think something like that could work? Or is there work to do in the final stage. I suspect it, but I wanted your input before making changes.
```
{
  extension: 'jpg',
  description: 'JPG | @:pipeline.high-quality-uncompressed',
  commands: [
    'mogrify @- -quality 92 scan-%04d.jpg',
    'ls scan-*.*'
  ]
}
```
Thank you! 
And thank you for scanservjs! pretty awesome as it is already!

**Comment by sbs20** [comment]
Hi @gortium - I suspect that what you're doing won't achieve what you want. I'm guessing you want multiple separate files as the output, yes? If scanservjs detects more than one output file, then it zips them all into a single file. So the pipeline won't help. Mogrify here is doing essentially the same as convert (which also operates on multiple files).

Perhaps what you *could* do (though it's a little hacky) is inject a pipeline command after the conversion, but before the final `ls scan-*.*` which copies the files as-is to where you want them. It's not ideal, but may achieve what you want.

**Comment by gortium** [comment]
Ho nice idea! I will try that! Thank you!
