### ISSUE TITLE
Progressive web app?

### ISSUE THREAD

**Issue by xeijin** [sbs20/scanservjs#385]
Hello! Many thanks for your hard work on this!

Just a thought but making this a simple PWA would be a great way to conveniently access it from the home screen of a smartphone.

https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Installable_PWAs

**Comment by sbs20** [comment]
Hello!

Thank you for the suggestion. I did briefly consider this as I've written PWAs elsewhere. For me, the primary advantage of PWAs is offline working. And that's not something that makes sense for this app since it requires access to the network in order to do anything at all.

It is possible to add bookmarks to the homescreen of your smartphone (both iOS and Android) which links direct to the app. Hopefully this meets your requirement. (It's what I do for that matter).

**Comment by xeijin** [comment]
Fair enough! I end up with alot of scanservjs tabs with add to homescreen but its not a big issue, thanks for your work on this.
