### ISSUE TITLE
Feature: merging scanned PDFs

### ISSUE THREAD

**Issue by ceskyDJ** [sbs20/scanservjs#431]
What about adding a feature that allows merging result PDFs in the "Files" section?

Today I found the first use case for this - I accidentally prematurely finished manual multi-page scanning, so I have to start a new scanning "session" and create two PDFs in scanservjs. After that, I must download the two documents, upload them to Adobe cloud to merge them and download them outside. It will be good to just select PDFs in scanservjs and click on "Merge documents" or something like that.

**Comment by sbs20** [comment]
This falls into the "too hard" category. Merging can involve many files and the order also matters - which requires that the UI also support it. So for now, I won't be doing this. If you find you've got otherwise good scans, then you can always just use `convert` at the command line to split the source files out into images and recombine.
