### ISSUE TITLE
Feature: renaming document title

### ISSUE THREAD

**Issue by ceskyDJ** [sbs20/scanservjs#432]
Now, only the file name is changed when I use rename tool included in scanservjs's "Files" section. When I open renames PDF in Adobe Acrobat, for example, it has an old title (like "scan-0000"). Could you add changing PDF's title, please?

It looks like the title is changed neither when renaming to the name with the date-time.

**Comment by sbs20** [comment]
Hi!

If you can find me a simple, reliable command line which will do it using the tools already used, then I will look into it. Rename at the moment literally just changes it on the filesystem and pays no attention at all to the file type.

It looks like imagemagick 7 supports something like it with [`-define`](https://imagemagick.org/script/defines.php) but this is currently using v6 I think.

Since I suspect it's not easily possible right now, I'm going to close this. But if you find that I'm wrong, just add a comment and I'll reopen.
