### ISSUE TITLE
Scanner device id changes on power cycle (scanimage: open of device $id failed: Invalid argument convert-im6.q16)

### ISSUE THREAD

**Issue by GG700** [sbs20/scanservjs#44]
Hi,

When I click on the "scan" button or on the "preview" button and when the USB scanner is not plugged (usb) or is off, the scanservjs returns an error (message in red font) : 

_Command failed: /usr/bin/scanimage -d "epson2:libusb:001:004" --mode "Color" --resolution 300 -l 0 -t 0 -x 215 -y 297 --format tiff | convert - jpg:- > "./data/output/scan_2020-07-03 16.46.03.jpg" scanimage: open of device epson2:libusb:001:004 failed: Invalid argument convert-im6.q16: no decode delegate for this image format `' @ error/constitute.c/ReadImage/560. convert-im6.q16: no images defined `jpg:-' @ error/convert.c/ConvertImageCommand/3258._ 

And then it is impossible to scan another time, even tough I plug the scanner. If I plug the scanner after, the command scanimage -L returns something like : 
device `epson2:libusb:001:004' is a Epson PID 08C8 flatbed scanner

If I want to scan again, I have to make a new install of scanerservjs : 

```
wget -O ~/scanservjs.tar.gz $(curl -s https://api.github.com/repos/sbs20/scanservjs/releases/latest | grep browser_download_url | cut -d '"' -f 4)
tar -xf scanservjs.tar.gz
sudo ./scanservjs/install.sh
rm scanservjs.tar.gz
rm -r scanservjs
```
When we click on "scan" or "preview", Is that possible that the command : 
scanimage -L returns something ?

**Comment by JnCrMx** [comment]
Could you please verify that the name shown by ``scanimage -L`` matches the name you can find in ``/var/www/scanservjs/device.conf``?

In your post, it looks like they match.

But I have experienced similar issues, which were caused by the system assigning a new name to the scanner every time it is plugged in (or switched on).

- Does the issue only happen after using "scan" or "preview" or also after just restarting/replugging the scanner?

- What exactly happens when you try to scan/preview after switching the scanner on again/plugging it in? Does the same error message show up?

**Comment by GG700** [comment]
You have true, after restarting the scanner, the name shown in _scanimage -L_ doesn't match with the name in _device.conf_.

After restarting the scanner, it is impossible to scan via scanservjs.

The error when I want to "scan" after restarting the scanner : 
_Command failed: /usr/bin/scanimage -d "epson2:libusb:001:007" --mode "Color" --resolution 300 -l 0 -t 0 -x 215 -y 297 --format tiff | convert - jpg:- > "./data/output/scan_2020-07-04 07.04.53.jpg" scanimage: open of device epson2:libusb:001:007 failed: Invalid argument convert-im6.q16: no decode delegate for this image format `' @ error/constitute.c/ReadImage/560. convert-im6.q16: no images defined `jpg:-' @ error/convert.c/ConvertImageCommand/3258._

The error when I want to "preview" after restarting the scanner : 
_Command failed: /usr/bin/scanimage -d "epson2:libusb:001:007" --mode "Color" --resolution 100 -l 0 -t 0 -x 215 -y 297 --format tiff > "./data/preview/preview.tif" scanimage: open of device epson2:libusb:001:007 failed: Invalid argument_ 

**>> I confirm that the system wants to change the number of device of the scanner at every restart of the device.**

**Comment by sbs20** [comment]
Can you confirm that just deleting `device.conf` resolves the issue? (you really shouldn't need to reinstall anything). When you reload the main page, it will force a recreation of the file.

Assuming so then this is just a cache invalidation problem.

`device.conf` is meant to save time with scanning because `scanimage -A` is slow (it takes about 10 seconds on my device). It would make everything take much longer.

We can just look for certain bad conditions (like the error message above) and delete the file.

**Comment by JnCrMx** [comment]
Since I had the same problem I have written a tiny script to work around this issue that (executed by ``udev`` every time the scanner is plugged in) updates the name stored in ``device.conf``:
```
#!/bin/bash

sed -i "s/\(epson2:libusb:001:\)[0-9]\+/\1$DEVNUM/" /var/www/scanservjs/device.conf
```

The corresponding ``udev``-rule looks like this:
```
ACTION=="bind", DRIVER=="usb", ATTRS{idVendor}=="<your vendor ID here>", ATTRS{idProduct}=="<your product ID here>", RUN+="<path to the script here>"
```

You can find the vendor and product IDs using ``lsusb`` or by looking in your Kernel's ``dmesg``.

**Comment by GG700** [comment]
@sbs20 : 

I deleted the file device.conf
The scanner was already on : the scan is ok.
I turned off, and then on the scanner : I have the same problem.

@JnCrMx 
I am not expert with linux : how do you execute the script you propose automatically with udev ?

**Comment by sbs20** [comment]
Ok. I think you need to delete the `device.conf` each time the scanner is turned on. It's not a long term solution but it saves you reinstalling each time. The `device.conf` has the device id in there which seems to change each time. @JnCrMx 's script will update the device id for you each time it's plugged in / switched on. This is also not a long term solution, but it will help in the interim while we figure out a solution.

**Comment by JnCrMx** [comment]
There is a subsystem called ``udev`` which can execute programs when a device is plugged in based on rules.

Those rules can (for example) be defined in ``/etc/udev/rules.d/``.
I placed a file called ``99-epson.rules`` there containing the following rule:
```
ACTION=="bind", DRIVER=="usb", ATTRS{idVendor}=="<your vendor ID here>", ATTRS{idProduct}=="<your product ID here>", RUN+="<path to the script here>"
```
You need to fill in the vendor and product ID of your scanner. Use ``lsusb`` to find those:
![image](https://user-images.githubusercontent.com/34038939/86511355-8cccea00-bdf8-11ea-8ed2-ad5dfdff488a.png)
(first number is vendor ID, second is product ID)

Then place the following script somewhere (e.g. in your home directory):
```sh
#!/bin/bash

sed -i "s/\(epson2:libusb:001:\)[0-9]\+/\1$DEVNUM/" /var/www/scanservjs/device.conf
```
Make it executable (using ``chmod +x <filename>``) and put the path to it in the udev-rule.

The rule then should look something like this (but with different IDs and a different path):
![image](https://user-images.githubusercontent.com/34038939/86511398-05cc4180-bdf9-11ea-89b5-81e9cd1a3486.png)

**Comment by GG700** [comment]
Thanks @sbs20  and @JnCrMx

**Comment by sbs20** [comment]
In order to get the device name the server needs to run `scanimage -A` which is a bit slow. For most use cases it's useful to cache this in a file. But in *this* instance the file is out of date since the device name changes. There's a new feature in `v2.0.0` which allows you to force get a new device config - it appears as a `Reinitialize` button. There may be a better way to achieve this with a bit more investigation, but it's an improvement.

**Comment by billyburrito** [comment]
I found a bit of a workaround, I aliased the device in the usb bus device tree...

```
root@scan:/etc/udev/rules.d# cat 70-uaccess.rules
SUBSYSTEMS=="usb", ATTRS{idVendor}=="04b8", ATTRS{idProduct}=="011e", MODE="0666", GROUP="scanner", ENV{libsane_matched}="yes", SYMLINK+="bus/usb/scanner"
```
When you symlink a device it defaults to /dev, you can just path it into the usb bus so that libusb calls will work against it.  Here is how I reference it in device.conf:

```
{
    "name": "epson2:libusb:scanner",
    #"name": "epson2:libusb:001:002",  # the old target
```

The OTG cable on my zero was quite unstable and my scanner would get a new ID each time, now it works everytime no matter how many reconnects it gets
