### ISSUE TITLE
Provide preset and configurable compression settings for formats

### ISSUE THREAD

**Issue by MrksHfmn** [sbs20/scanservjs#47]
After scanning Text with 300dpi and no colour the PDF (one page) is aorund 10-13 MB big. It's possible to minify the with ghostscript (ps2pdf big.pdf small.pdf) to about 0,3 MB.

**Comment by whysthatso** [comment]
i think that there's an assumption on what kind of quality output one needs.
talking to a professional graphic designer/printer they would always tell you to go with 300dpi as this is standard printing quality, i think. so a doc management that has the assumption that one would want to eventually print the docs again, actually should go with this default.

however, i do agree that it would be amazing to have some converting options, based on the output format one chooses to convert to. maybe that's a compromise?

i think scanning at a lower dpi is not comparable to using a compression algorithm after the fact, i think a compression is 'smarter' then just bluntly scanning at lower resolution.

as you can probably tell, i've been trying to figure this out since some time, going through edms like mayan, paperless and papermerge in conjuction with a scanning server. however, none of these edms explain very well the implications of different scan resolutions or compressions. i think this might be good to reference in the docs, if anybody knows more about this stuff or comes across a good documentation.
