### ISSUE TITLE
Scanner height of 296.926mm

### ISSUE THREAD

**Issue by splithor1zon** [sbs20/scanservjs#552]
**Describe the bug**
Some scanners such as HP LaserJet M1005 using hplip driver report height limit of 296.926mm. This causes the A4 paper size option to not appear in the frontend. I bypassed this behavior by modifying the filter function by adding +1 to the limit value in the index js file (so the A4 paper size won't get filtered).

**To Reproduce**
From devices.json :

`"\nAll options specific to device 'hpaio:/usb/HP_LaserJet_M1005?serial=KJ241N9':\n  Scan mode:\n    --mode Lineart|Gray|Color [Lineart]\n        Selects the scan mode (e.g., lineart, monochrome, or color).\n    --resolution 75|100|150|200|300|600|1200dpi [75]\n        Sets the resolution of the scanned image.\n    --source Flatbed [Flatbed]\n        Selects the scan source (such as a document-feeder).\n  Advanced:\n    --contrast 1..11 [6]\n        Controls the contrast of the acquired image.\n    --brightness 0..200 [6]\n        Controls the brightness of the acquired image.\n  Geometry:\n    -l 0..215.9mm [0]\n        Top-left x position of scan area.\n    -t 0..296.926mm [0]\n        Top-left y position of scan area.\n    -x 0..215.9mm [215.9]\n        Width of scan-area.\n    -y 0..296.926mm [296.926]\n        Height of scan-area.\n\n"`

**Expected behavior**
Show A4 option in the frontend.

**Possible solution**
Notice the +1 at the end
`paperSizes:function(){var e=this;if(this.geometry){var t={x:this.device.features["-x"].limits[1],y:this.device.features["-y"].limits[1]+1};`

**Comment by sbs20** [comment]
Hi, thanks for posting.

The problem here is that A4 is 297 x 210, which means whichever way we cut it, your scanner is smaller than A4, so the app won't let you do it. Further, the backend will constrain the dimensions to the scanner size, and if it didn't the scan command would fail. And if I changed the size of A4 instead then everyone else would rightly complain that A4 is wrong.

The app is behaving correctly and as expected.

However, there is a solution for you. You can override the paper size setting and pretend that A4 is marginally smaller than it really is.

Follow the instructions to [override configuration](https://github.com/sbs20/scanservjs/blob/master/docs/config.md#configuration-and-integration), do something like the following and restart.

```javascript
module.exports = {
  /**
   * @param {Configuration} config 
   */
  afterConfig(config) {
    config.paperSizes
      .filter(p => p.name.startsWith('A4'))
      .forEach(p => {
        p.dimensions.y = 296.9;
      });
  },
};
```
