### ISSUE TITLE
Arch AUR Package

### ISSUE THREAD

**Issue by sbs20** [sbs20/scanservjs#660]
With version 3 coming up, there are some notable changes to the overall build.

1. It is now updated to use vue3 annd vite - so no more webpack; this makes everything compatible with Node 18 and beyond - not to mention much faster to build.
2. the distribution asset will be a `.deb` package. This an `ar` archive with some nested tarballs and installation scripts

Before everything is committed to mainline and released I wanted to see if there was anything I could do to make things better or easier for the Arch AUR maintenance.

**Comment by dadosch** [comment]
Hi, so I've noticed that the systemd service has been integrated into the Debian packaging script, but this is not a problem, since I can just put the service inside the AUR git repo (and I suppose there won't be any big changes there).
Also as I am not totally fond with vue and npm in its specifics, I want to verify that the building commands looks correct to you:

   npm run build:version && npm run build --workspaces && node build.js --assemble
   npm install --production

I've adopted the PKGBUILD file, and it builds succesfully, but I didn't have time yet to test it.

**Comment by sbs20** [comment]
Closing because there's nothing more I can do here. If you need any assistance drop a note here and I'll do whatever I can to help.
