### ISSUE TITLE
Inline image filters e.g. black-and-white format

### ISSUE THREAD

**Issue by mildfuzz** [sbs20/scanservjs#98]
According to the (scanimage docs)[https://linux.die.net/man/1/scanimage] there is a `black-and-white` format. 

I believe this will mirror the black and white mode in my devices Windows software, but I am unable to select this from the UI. Is this trivial to add?

**Comment by mildfuzz** [comment]
FYI, happy to dive into code and have a go with some guidance 😃

**Comment by sbs20** [comment]
Normally the scanner declares its modes when you do a `scanimage -A`. This should be presented to you as an option in the UI if it's there. If not, there's not currently a way around that.

Example output here : https://github.com/sbs20/scanservjs/blob/master/test/resource/scanimage-a1.txt

Any use?

**Comment by mildfuzz** [comment]
so a couple of things I have discovered. 

Firstly, there is a despeckle flag on scanimage. This does go some way to improve noisy scans

But doing some A / B comparisons about what is coming out of the manufacturers results, and what is coming out of scanimage results, I am pretty certain that "black and white" is actually a grey scan, followed by a theshold filter. I experimented with imagemackic's colorThreshold and it seems cutting off grays lighter than rgb(130,130,130) seem to produce comparible results to the Canonscan "black and white" filter.

**Comment by JnCrMx** [comment]
The thing about ``scanimage`` is that it is a very simple frontend to SANE and mostly only forwards options to the backend.
Therefore, most options (including ``--mode`` and apparently also the despeckle flag) actually depend on the backend, which means that they might differ from scanner to scanner.
A few options are independent (https://gitlab.com/sane-project/backends/-/blob/master/frontend/scanimage.c#L2295) but they mostly just select a device, control batch mode, etc.

You can distinguish between them by doing ``scanimage --help`` and look for a short pause in execution. Options printed before that pause are backend-independent, while the ones after the pause (if there are any) are backend-dependent, Those backend-dependent options are also proceeded by a ``Options specific to device `<your device name>':``.

For some of these options it might be reasonable to assume that every backend accepts and implements them, but you cannot really rely on that for all options.

A way around this trouble with backend-dependent options might be to completely dynamically build the UI based on the options received from ``scanimage -A``, but that would require a lot of work. Also, there is the issue of finding out what type and constraints (e.g. switch, range, list) the option has; this problem was sort of discussed in #42.

In theory there is an API for fetching all available options (including their type, constraints, etc.) which is documented at http://www.sane-project.org/html/doc009.html. It also includes useful information about how exactly options work (http://www.sane-project.org/html/doc011.html#s4.2.9).
Using this API seems to require native code though, so I'm not sure if that would be a good option.

**Comment by sbs20** [comment]
First off, thanks for taking the time to raise this and do some research. I've been having a think about this issue.

In principle I want to make the project as useful as possible for people - and a black and white scan could be useful. added to which it would be nice for it not to be step down from using the native software.

* The challenge is that it needs to support all scanners and not all scanners support all modes - and not only that but they report different mode names so it's difficult (impossible?) to account for all possible options in advance.
* Therefore I think using `scanimage` to do the work is probably a bad idea
* That leaves the option of adding pipelines and `convert` to perform post-processing (use the colorThreshold option you found). This isn't such a bad approach: it's more flexible and could work on any input.
* The problem (as it currently stands) is that there's only one "pipeline" (format) which is selectable in the UI, so if we wanted to add a `black and white`, we'd need to do so for each of the output formats - doubling the number of pipelines. Less good.
* I did toy with the idea, when doing v2, of being able to select multiple pipelines - this would be much more powerful... `raw -> b&w -> jpg > pdf`. It would also be possible to add even more filters such as blur / smooth / sharpen / whatever.
But this starts to make the UI more difficult to use, order of pipelines matter, There could be a "simple" and "advanced" mode which ties different pipelines together in easy ways for the user.

I'm not completely against this approach but it's a lot of effort. For my own *personal* use case, though, I'm not convinced I would need it. I either just want to scan a simple document in which case mode: Gray and format JPG / PDF would be fine giving a balance of ease / size / speed / format... or I want to scan a photo in which case I want TIF and I use Photoshop / Gimp / Irfanview to clean it up.

My use case may not be the consensus, however. So I will leave this issue open here and other can vote. If there's enough interest, then I will give it more thought and give it a go.

**Comment by JnCrMx** [comment]
I generally like the idea of being able to select multiple pipelines. It might also be a nice idea to have pipeline definitions that are made of other pipelines that then replace the pipelines made of multiple ``convert`` commands.

But while it is something very cool in theory, I would most likely not really use it. Personally I usually just do simple JPEG or PDF scans and don't really need special features or post-processing. Nevertheless - as you said - it might be useful for some other users.

Also, I agree that there should be an "advanced mode" for this or multiple pipelines would be incredibly confusing for the normal user and hence defeating simplicity and purpose of the application.
